// Translations object containing the English and Georgian text
const translations = {
    "en": {
        "homeLink": "Home",
        "aboutLink": "About",
        "servicesLink": "Services",
        "contactLink": "Contact",
        "loginBtn": "Login",
        "registerBtn": "Register",
        "menuTitle": "Our Coffee Menu",
        "espresso": "Espresso",
        "espressoDesc": "A rich and bold coffee served in a small cup.",
        "espressoPrice": "5.50 GEL",
        "cappuccino": "Cappuccino",
        "cappuccinoDesc": "A smooth espresso topped with steamed milk and frothy foam.",
        "cappuccinoPrice": "7.00 GEL",
        "latte": "Latte",
        "latteDesc": "A creamy espresso combined with steamed milk.",
        "lattePrice": "11.20 GEL",
        "americano": "Americano",
        "americanoDesc": "Espresso mixed with hot water, creating a light flavor.",
        "americanoPrice": "6.00 GEL",
        "mocha": "Mocha",
        "mochaDesc": "A blend of espresso, steamed milk, and chocolate syrup.",
        "mochaPrice": "8.00 GEL",
        "macchiato": "Macchiato",
        "macchiatoDesc": "Espresso with a splash of steamed milk.",
        "macchiatoPrice": "6.50 GEL",
        "flatWhite": "Flat White",
        "flatWhiteDesc": "Espresso with smooth steamed milk for a velvety taste.",
        "flatWhitePrice": "7.50 GEL",
        "affogato": "Affogato",
        "affogatoDesc": "A scoop of vanilla ice cream topped with hot espresso.",
        "affogatoPrice": "9.00 GEL",
        "icedLatte": "Iced Latte",
        "icedLatteDesc": "Espresso with chilled milk and ice for a refreshing taste.",
        "icedLattePrice": "7.00 GEL",
        "icedCoffee": "Iced Coffee",
        "icedCoffeeDesc": "Cold brewed coffee served over ice.",
        "icedCoffeePrice": "6.00 GEL",
        "latteArt": "Latte Art",
        "latteArtDesc": "Latte with beautifully crafted designs in the foam.",
        "latteArtPrice": "8.50 GEL",
        "coldBrew": "Cold Brew",
        "coldBrewDesc": "Cold brewed coffee served over ice for a smoother flavor.",
        "coldBrewPrice": "6.50 GEL",
        "irishCoffee": "Irish Coffee",
        "irishCoffeeDesc": "Espresso with Irish whiskey, sugar, and cream.",
        "irishCoffeePrice": "10.00 GEL",
        "brazilianCoffee": "Brazilian Coffee",
        "brazilianCoffeeDesc": "Brazilian coffee beans brewed for a bold, rich flavor.",
        "brazilianCoffeePrice": "6.00 GEL",
        "swissCoffee": "Swiss Coffee",
        "swissCoffeeDesc": "A blend of espresso, chocolate, and steamed milk.",
        "swissCoffeePrice": "9.00 GEL",
        "decaf": "Decaf Coffee",
        "decafDesc": "Perfectly brewed coffee with no caffeine.",
        "decafPrice": "5.00 GEL",
        "caramelMacchiato": "Caramel Macchiato",
        "caramelMacchiatoDesc": "Espresso with steamed milk and caramel drizzle.",
        "caramelMacchiatoPrice": "8.50 GEL",
        "vanillaLatte": "Vanilla Latte",
        "vanillaLatteDesc": "Espresso with steamed milk and a touch of vanilla syrup.",
        "vanillaLattePrice": "8.00 GEL",
        "coffeeSmoothie": "Coffee Smoothie",
        "coffeeSmoothieDesc": "A creamy, cold coffee smoothie blended with ice.",
        "coffeeSmoothiePrice": "7.50 GEL",
        "footerText": "© 2024 Coffee Shop. All rights reserved."
    },
    "ka": {
        "homeLink": "მთავარი",
        "aboutLink": "ჩვენ შესახებ",
        "servicesLink": "სერვისები",
        "contactLink": "კონტაქტი",
        "loginBtn": "შესვლა",
        "registerBtn": "რეგისტრაცია",
        "menuTitle": "ჩვენი ყავის მენიუ",
        "espresso": "ესპრესო",
        "espressoDesc": "მდიდარი და ძლიერი ყავა, რომელიც მინი ჭიქაში ემსახურება.",
        "espressoPrice": "5.50 GEL",
        "cappuccino": "კაპუჩინო",
        "cappuccinoDesc": "მოხერხებული ესპრესო, რომელიც დაფარულია შეწურული რძითა და მუქი ქაფით.",
        "cappuccinoPrice": "7.00 GEL",
        "latte": "ლატე",
        "latteDesc": "კრემისებრი ესპრესო, რომელიც შერწყმულია შეწურულ რძესთან.",
        "lattePrice": "11.20 GEL",
        "americano": "ამერიკანო",
        "americanoDesc": "ესპრესო შერეული ცხელი წყლით, რაც ქმნის მსუბუქ გემოს.",
        "americanoPrice": "6.00 GEL",
        "mocha": "მოკა",
        "mochaDesc": "ესპრესო, შეწურული რძე და შოკოლადის სიროფი.",
        "mochaPrice": "8.00 GEL",
        "macchiato": "მაკიატო",
        "macchiatoDesc": "ესპრესო თხელი რძის დამატებით.",
        "macchiatoPrice": "6.50 GEL",
        "flatWhite": "ფლატ უაითი",
        "flatWhiteDesc": "ესპრესო დამუშავებული რძით და სქელი გემოთი.",
        "flatWhitePrice": "7.50 GEL",
        "affogato": "აფოგატო",
        "affogatoDesc": "ვანილის აისკრიმი ცხელი ესპრესოთი.",
        "affogatoPrice": "9.00 GEL",
        "icedLatte": "ყინული ლატე",
        "icedLatteDesc": "ესპრესო გაყინული რძითა და ყინულით.",
        "icedLattePrice": "7.00 GEL",
        "icedCoffee": "ყინულიანი ყავა",
        "icedCoffeeDesc": "ცივი დუღილი ყავა ყინულით.",
        "icedCoffeePrice": "6.00 GEL",
        "latteArt": "ლატე არტი",
        "latteArtDesc": "ლატე მშვენიერი დიზაინებით.",
        "latteArtPrice": "8.50 GEL",
        "coldBrew": "ცივი დუღილი",
        "coldBrewDesc": "ცივი დუღილი ყავა უფრო სქელი გემოთი.",
        "coldBrewPrice": "6.50 GEL",
        "irishCoffee": "ირლანდიური ყავა",
        "irishCoffeeDesc": "ესპრესო ირლანდიურ როჟას, შაქარითა და კრემით.",
        "irishCoffeePrice": "10.00 GEL",
        "brazilianCoffee": "ბრაზილიური ყავა",
        "brazilianCoffeeDesc": "ბრაზილიური ყავის მარცვლები გემოს მეტი მდიდარი გემოთი.",
        "brazilianCoffeePrice": "6.00 GEL",
        "swissCoffee": "შვეიცარული ყავა",
        "swissCoffeeDesc": "ესპრესო შოკოლადთან და რძესთან.",
        "swissCoffeePrice": "9.00 GEL",
        "decaf": "დეკაფი",
        "decafDesc": "ყავა, რომელიც არ შეიცავს კოფეინს.",
        "decafPrice": "5.00 GEL",
        "caramelMacchiato": "კარამელ მაკიატო",
        "caramelMacchiatoDesc": "ესპრესო შეწურული რძით და კარამელის სიროფით.",
        "caramelMacchiatoPrice": "8.50 GEL",
        "vanillaLatte": "ვანილის ლატე",
        "vanillaLatteDesc": "ესპრესო შეწურული რძით და ვანილის სიროფით.",
        "vanillaLattePrice": "8.00 GEL",
        "coffeeSmoothie": "ყავის სმუზი",
        "coffeeSmoothieDesc": "კრემისებრი ყავა გამყინავი ყინულით.",
        "coffeeSmoothiePrice": "7.50 GEL",
        "footerText": "© 2024 ყავის მაღაზია. ყველა უფლება დაცულია.",
        
    }
};

// Function to change the text content based on selected language
function changeLanguage(language) {
    // Iterate over all keys in the translations object and change the text content
    for (const key in translations[language]) {
        const element = document.getElementById(key);
        if (element) {
            element.textContent = translations[language][key];
        }
    }
}
